### ISSUE TITLE
Cloudformation Changes?

### ISSUE THREAD

**Issue by tuffacton** [ACloudGuru-Resources/Course_Introduction_to_Ansible#3]
Trying to follow along with chapter 2.2 and I think maybe AWS has changed Cloudformation setups since then. After importing yaml from [here](https://github.com/ACloudGuru-Resources/Course_Introduction_to_Ansible/blob/master/02_02_Introduction_To_Ansible/setup-env.yml) I'm asked to identify additional resources outside of the scope of the video.

**Comment by brocktubre** [comment]
Hi @tuffacton, 

I uploaded the CloudFormation template without any errors or issues. Could you please let us know what errors you are getting when trying upload and create the ClodFormation stack? The only issue that comes to mind is if you do not have a default VPC setup or associated with the region you are currently in. 

Also, for a faster response,  please use the ACG forums associated with the video lectures on the ACG platform. I get regular emails when students post questions and it's also a great place for other students to see any issues! 👍

**Comment by cargillchantry** [comment]
I had to specify IP addresses for the ec2 instances along with identifiers. Following that I got this error.

```The following resources to import [LnElasticIp1, LnEc2InstanceWebServer1, LnEc2InstanceWebServer2, LnElasticIp2, LnElasticIp3, LnSecurityGroup, LnEc2InstanceLoadBalancer] must have DeletionPolicy attribute specified in the template.```

The solution is to update the yaml to specify a [deletion policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html).

**Comment by cargillchantry** [comment]
Ah scratch the above. I had mistakenly gone create -> with existing resources. We want to select "with new resources (standard)".
